In [2]:
import numpy as np
from PIL import Image
import os
import pandas as pd


# Load in data subset


In [4]:
# Directory containing JPEG images
image_dir = '/Users/matthewdavidson/CS156bProject/data_subset/train_data_subset'

# List to store image data
image_data = []

# Loop through all files in the directory
for filename in os.listdir(image_dir):
    if filename.endswith('.jpg'):
        # Construct the full path to the image file
        file_path = os.path.join(image_dir, filename)
        
        # Open the image using PIL
        img = Image.open(file_path)
        
        # Convert the image to a NumPy array or any other data processing you need
        img_array = np.array(img)
        
        # Append the image array and filename to the image_data list
        image_data.append({'filename': filename, 'image_data': img_array})

# Convert the image data list to a pandas DataFrame
image_df = pd.DataFrame(image_data)

# Print the DataFrame (optional)
print(image_df)

# Now you can perform data analysis on the image_df DataFrame
# For example, you can access image data by filename:
# image_row = image_df[image_df['filename'] == 'image_0.jpg']
# image_array = image_row['image_data'].values[0]


          filename                                         image_data
0    image_178.jpg  [[33, 32, 32, 30, 31, 31, 29, 32, 32, 29, 32, ...
1    image_150.jpg  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...
2    image_144.jpg  [[33, 29, 27, 27, 26, 24, 21, 18, 15, 4, 1, 0,...
3     image_15.jpg  [[22, 19, 17, 17, 17, 18, 17, 17, 17, 20, 19, ...
4     image_29.jpg  [[102, 106, 115, 96, 99, 119, 93, 102, 123, 10...
..             ...                                                ...
174   image_30.jpg  [[37, 37, 38, 38, 38, 37, 36, 35, 38, 36, 37, ...
175   image_18.jpg  [[21, 22, 23, 22, 17, 16, 23, 16, 16, 3, 17, 1...
176  image_149.jpg  [[13, 14, 15, 13, 12, 3, 3, 5, 5, 1, 5, 5, 11,...
177  image_161.jpg  [[11, 12, 13, 13, 12, 12, 12, 12, 10, 13, 13, ...
178  image_175.jpg  [[29, 55, 31, 21, 28, 66, 37, 65, 62, 66, 67, ...

[179 rows x 2 columns]


In [11]:
print(image_df['image_data'])

[[33 32 32 ... 35 34 34]
 [32 31 31 ... 34 34 34]
 [31 30 31 ... 34 35 35]
 ...
 [25 24 27 ... 67 52 49]
 [27 30 24 ... 69 54 46]
 [29 29 23 ... 75 60 48]]
