In [247]:
import numpy as np
from PIL import Image
import os
import pandas as pd
import matplotlib.pyplot as plt

# Functions

In [248]:
# Assuming image_df is your DataFrame with filename and image_data columns
# Function to display images from pixel data
def display_image(pixel_data):
    plt.imshow(pixel_data, cmap='gray')  # Display the image using grayscale colormap
    plt.axis('off')  # Turn off axis labels
    plt.show()

# Load in data subset


# Image Data Subset


In [249]:
# Directory containing JPEG images
image_dir = '/Users/matthewdavidson/CS156bProject/data_subset/train_data_subset'

# List to store image data
image_data = []

# Loop through all files in the directory
for filename in os.listdir(image_dir):
    if filename.endswith('.jpg'):
        # Construct the full path to the image file
        file_path = os.path.join(image_dir, filename)
        
        # Open the image using PIL
        img = Image.open(file_path)
        
        # Convert the image to a NumPy array or any other data processing you need
        img_array = np.array(img)
        
        # Append the image array and filename to the image_data list
        image_data.append({'filename': filename, 'image_data': img_array})

# Convert the image data list to a pandas DataFrame
image_df = pd.DataFrame(image_data)

# Print the DataFrame (optional)
print(image_df)

# Now you can perform data analysis on the image_df DataFrame
# For example, you can access image data by filename:
# image_row = image_df[image_df['filename'] == 'image_0.jpg']
# image_array = image_row['image_data'].values[0]

          filename                                         image_data
0    image_178.jpg  [[33, 32, 32, 30, 31, 31, 29, 32, 32, 29, 32, ...
1    image_150.jpg  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...
2    image_144.jpg  [[33, 29, 27, 27, 26, 24, 21, 18, 15, 4, 1, 0,...
3     image_15.jpg  [[22, 19, 17, 17, 17, 18, 17, 17, 17, 20, 19, ...
4     image_29.jpg  [[102, 106, 115, 96, 99, 119, 93, 102, 123, 10...
..             ...                                                ...
174   image_30.jpg  [[37, 37, 38, 38, 38, 37, 36, 35, 38, 36, 37, ...
175   image_18.jpg  [[21, 22, 23, 22, 17, 16, 23, 16, 16, 3, 17, 1...
176  image_149.jpg  [[13, 14, 15, 13, 12, 3, 3, 5, 5, 1, 5, 5, 11,...
177  image_161.jpg  [[11, 12, 13, 13, 12, 12, 12, 12, 10, 13, 13, ...
178  image_175.jpg  [[29, 55, 31, 21, 28, 66, 37, 65, 62, 66, 67, ...

[179 rows x 2 columns]


# Label Data Subset

In [250]:
# File path to the CSV file
csv_file = '/Users/matthewdavidson/CS156bProject/CS156b/Data/train2023.csv'

# Read the CSV file into a DataFrame
full_df = pd.read_csv(csv_file)
print(full_df.head())

# Extract the labels from the DataFrame
labels = full_df.columns[6:]  # Assuming the labels start from the 7th column (index 6) onwards

# Print the extracted labels
#print("Extracted labels:")
#(labels)

   Unnamed: 0.1  Unnamed: 0                                     Path     Sex  \
0             0           0  train/pid50512/study1/view1_frontal.jpg  Female   
1             1           1  train/pid21580/study2/view1_frontal.jpg  Female   
2             2           2  train/pid21580/study1/view1_frontal.jpg  Female   
3             3           3  train/pid21580/study1/view2_lateral.jpg  Female   
4             4           4  train/pid33839/study1/view1_frontal.jpg    Male   

   Age Frontal/Lateral AP/PA  No Finding  Enlarged Cardiomediastinum  \
0   68         Frontal    AP         1.0                         NaN   
1   87         Frontal    AP         NaN                         NaN   
2   83         Frontal    AP         NaN                         NaN   
3   83         Lateral   NaN         NaN                         NaN   
4   41         Frontal    AP         NaN                         NaN   

   Cardiomegaly  Lung Opacity  Pneumonia  Pleural Effusion  Pleural Other  \
0        

# Import Label for Image Subset

In [251]:
# Load the NumPy array containing data
data_array = np.load('/Users/matthewdavidson/CS156bProject/train_data_subset.npy')
# Function to edit file paths
def edit_file_path(path):
    # Split the path by '/'
    parts = path.split('/')
    # Extract the relevant parts (assuming the format is consistent)
    relevant_parts = parts[4:]  # Adjust the index based on your path structure
    # Join the relevant parts to create the new path format
    new_path = '/'.join(relevant_parts)
    return new_path

# Apply the edit_file_path function to each path in data_array
path_array = [edit_file_path(path) for path in data_array]
(path_array)


['train/pid50512/study1/view1_frontal.jpg',
 'train/pid29112/study1/view2_lateral.jpg',
 'train/pid01032/study2/view1_frontal.jpg',
 'train/pid22981/study1/view1_frontal.jpg',
 'train/pid50403/study2/view1_frontal.jpg',
 'train/pid16802/study3/view1_frontal.jpg',
 'train/pid40709/study4/view2_lateral.jpg',
 'train/pid21394/study1/view1_frontal.jpg',
 'train/pid30713/study5/view1_frontal.jpg',
 'train/pid05474/study1/view2_lateral.jpg',
 'train/pid32143/study3/view1_frontal.jpg',
 'train/pid12801/study14/view2_lateral.jpg',
 'train/pid45962/study1/view1_frontal.jpg',
 'train/pid43778/study32/view1_frontal.jpg',
 'train/pid09135/study1/view1_frontal.jpg',
 'train/pid11731/study5/view1_frontal.jpg',
 'train/pid42849/study1/view2_lateral.jpg',
 'train/pid34488/study2/view1_frontal.jpg',
 'train/pid06670/study11/view1_frontal.jpg',
 'train/pid42109/study1/view1_frontal.jpg',
 'train/pid23745/study5/view2_lateral.jpg',
 'train/pid41770/study3/view1_frontal.jpg',
 'train/pid01641/study12/view

# Join Proper Labels with images in Image Subset. 


In [252]:
# Filter full_df based on paths in data_array
filtered_df = full_df[full_df['Path'].isin(path_array)]

# Print the filtered DataFrame
#print(filtered_df)

# Extract the labels from the DataFrame
filtered_labels = filtered_df.columns[6:]  # Assuming the labels start from the 7th column (index 6) onwards

# Print the extracted labels
#print("Extracted labels:")
#print(filtered_labels)

# Extract only the columns containing label data
label_columns = filtered_df.columns[6:]  # Assuming the labels start from the 7th column (index 6) onwards
filtered_label_df = filtered_df[label_columns]

# Print the filtered DataFrame containing only the label data
print("DataFrame of filtered labels:")
(filtered_label_df)


DataFrame of filtered labels:


AP/PA  No Finding  Enlarged Cardiomediastinum  Cardiomegaly  \
0         AP         1.0                         NaN           NaN   
1000     NaN         1.0                         NaN           NaN   
2000      PA         1.0                         NaN           NaN   
3000      AP         1.0                        -1.0           NaN   
4000      AP         NaN                         NaN           NaN   
...      ...         ...                         ...           ...   
174000    AP         1.0                         NaN           NaN   
175000   NaN         NaN                         NaN           NaN   
176000    AP         NaN                         NaN           NaN   
177000    AP         NaN                         NaN           NaN   
178000    AP         NaN                         1.0           NaN   

        Lung Opacity  Pneumonia  Pleural Effusion  Pleural Other  Fracture  \
0                NaN        NaN               NaN            NaN       NaN   
1000             NaN        NaN               0.0            NaN       NaN   
2000             NaN        NaN              -1.0            NaN       NaN   
3000            -1.0        NaN              -1.0            NaN       NaN   
4000             NaN        NaN               NaN            NaN       NaN   
...              ...        ...               ...            ...       ...   
174000           NaN        NaN               NaN            NaN       NaN   
175000           NaN        NaN               NaN            NaN       NaN   
176000           1.0        NaN               1.0            NaN       NaN   
177000           1.0        NaN               1.0            NaN       NaN   
178000           1.0        NaN               NaN            NaN       NaN   

        Support Devices  
0                   1.0  
1000                1.0  
2000                NaN  
3000                NaN  
4000                NaN  
...                 ...  
174000              1.0  
175000              1.0  
176000              NaN  
177000              1.0  
178000              1.0  

[179 rows x 10 columns]

# Merged Data frames

In [253]:
# Reset the index of both DataFrames to ensure they align row by row during concatenation
filtered_labels_df = filtered_label_df.reset_index(drop=True, inplace=False)
#print(filtered_labels_df)
# Concatenate the DataFrames along axis 1 (columns), which will align them row by row
merged_df = pd.concat([image_df, filtered_labels_df], axis=1)

# Print the merged DataFrame to verify the merge
print("Merged DataFrame:")
(merged_df.head())

Merged DataFrame:


filename                                         image_data AP/PA  \
0  image_178.jpg  [[33, 32, 32, 30, 31, 31, 29, 32, 32, 29, 32, ...    AP   
1  image_150.jpg  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...   NaN   
2  image_144.jpg  [[33, 29, 27, 27, 26, 24, 21, 18, 15, 4, 1, 0,...    PA   
3   image_15.jpg  [[22, 19, 17, 17, 17, 18, 17, 17, 17, 20, 19, ...    AP   
4   image_29.jpg  [[102, 106, 115, 96, 99, 119, 93, 102, 123, 10...    AP   

   No Finding  Enlarged Cardiomediastinum  Cardiomegaly  Lung Opacity  \
0         1.0                         NaN           NaN           NaN   
1         1.0                         NaN           NaN           NaN   
2         1.0                         NaN           NaN           NaN   
3         1.0                        -1.0           NaN          -1.0   
4         NaN                         NaN           NaN           NaN   

   Pneumonia  Pleural Effusion  Pleural Other  Fracture  Support Devices  
0        NaN               NaN            NaN       NaN              1.0  
1        NaN               0.0            NaN       NaN              1.0  
2        NaN              -1.0            NaN       NaN              NaN  
3        NaN              -1.0            NaN       NaN              NaN  
4        NaN               NaN            NaN       NaN              NaN

# Convert NaN values to 0

used to denote uncertain or unspecified diagnosis to model 


In [254]:
# Assuming merged_df is your merged DataFrame

# Replace NaN values with 0
merged_df.fillna(0, inplace=True)
#merged_df.drop(['level_0', 'index'], axis=1, inplace=True)

# Print the modified DataFrame to verify the changes
(merged_df.head())

filename                                         image_data AP/PA  \
0  image_178.jpg  [[33, 32, 32, 30, 31, 31, 29, 32, 32, 29, 32, ...    AP   
1  image_150.jpg  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...     0   
2  image_144.jpg  [[33, 29, 27, 27, 26, 24, 21, 18, 15, 4, 1, 0,...    PA   
3   image_15.jpg  [[22, 19, 17, 17, 17, 18, 17, 17, 17, 20, 19, ...    AP   
4   image_29.jpg  [[102, 106, 115, 96, 99, 119, 93, 102, 123, 10...    AP   

   No Finding  Enlarged Cardiomediastinum  Cardiomegaly  Lung Opacity  \
0         1.0                         0.0           0.0           0.0   
1         1.0                         0.0           0.0           0.0   
2         1.0                         0.0           0.0           0.0   
3         1.0                        -1.0           0.0          -1.0   
4         0.0                         0.0           0.0           0.0   

   Pneumonia  Pleural Effusion  Pleural Other  Fracture  Support Devices  
0        0.0               0.0            0.0       0.0              1.0  
1        0.0               0.0            0.0       0.0              1.0  
2        0.0              -1.0            0.0       0.0              0.0  
3        0.0              -1.0            0.0       0.0              0.0  
4        0.0               0.0            0.0       0.0              0.0

# Normalization

In [ ]:
# Create a histogram of pixel values for the first image in the DataFrame
first_image_data = image_df.iloc[0]['image_data']  # Assuming the first image in the DataFrame
pixel_values = first_image_data.flatten()

# Plot the histogram
plt.figure(figsize=(10, 6))
plt.hist(pixel_values, bins=256, range=(0, 255), density=True, color='blue', alpha=0.7)
plt.xlabel('Pixel Value')
plt.ylabel('Frequency')
plt.title('Histogram of Pixel Values')
plt.grid(True)
plt.show()

# Normalize the image data (assuming min-max normalization)
normalized_image_data = (first_image_data - np.min(first_image_data)) / (np.max(first_image_data) - np.min(first_image_data))
normalized_pixel_values = normalized_image_data.flatten()

# Plot the histogram
plt.figure(figsize=(10, 6))
plt.hist(normalized_pixel_values, bins=256, range=(0,1), density=True, color='blue', alpha=0.7)
plt.xlabel('Pixel Value')
plt.ylabel('Frequency')
plt.title('Histogram of Normalized Pixel Values')
plt.grid(True)
plt.show()

# Print the normalized image data (optional)
print("Normalized Image Data:")
print(normalized_image_data)

In [ ]:
display_image(first_image_data)
print(f'first image data: {first_image_data}')

In [ ]:
display_image(normalized_image_data)
print(f'normalized image data: {normalized_image_data}')

In [258]:
# Display images from image_df DataFrame
'''
for index, row in image_df.iterrows():
    filename = row['filename']
    image_data = row['image_data']
    print(f"Displaying image: {filename}")
    display_image(image_data)
    '''

'\nfor index, row in image_df.iterrows():\n    filename = row[\'filename\']\n    image_data = row[\'image_data\']\n    print(f"Displaying image: {filename}")\n    display_image(image_data)\n    '

# Convolutional Neural Network


In [259]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.image import resize

In [266]:
merged_df['image_data'] = merged_df['image_data'].apply(tf.convert_to_tensor)
print(merged_df['image_data'])

0      ((tf.Tensor(33, shape=(), dtype=uint8), tf.Ten...
1      ((tf.Tensor(2, shape=(), dtype=uint8), tf.Tens...
2      ((tf.Tensor(33, shape=(), dtype=uint8), tf.Ten...
3      ((tf.Tensor(22, shape=(), dtype=uint8), tf.Ten...
4      ((tf.Tensor(102, shape=(), dtype=uint8), tf.Te...
                             ...                        
174    ((tf.Tensor(37, shape=(), dtype=uint8), tf.Ten...
175    ((tf.Tensor(21, shape=(), dtype=uint8), tf.Ten...
176    ((tf.Tensor(13, shape=(), dtype=uint8), tf.Ten...
177    ((tf.Tensor(11, shape=(), dtype=uint8), tf.Ten...
178    ((tf.Tensor(29, shape=(), dtype=uint8), tf.Ten...
Name: image_data, Length: 179, dtype: object


In [270]:
print(merged_df['image_data'][0].shape[0])
print(merged_df['image_data'][0].shape[1])
print(len(merged_df['image_data']))
print(merged_df['image_data'][7])

2320
2828
179
tf.Tensor(
[[ 0  0  0 ... 13  8 11]
 [ 0  0  0 ... 10  8 11]
 [ 0  0  0 ... 10  9 12]
 ...
 [ 8 13 10 ...  2  0  0]
 [11 14 10 ...  0  0  0]
 [ 7 14 15 ...  1  2  2]], shape=(2048, 2494), dtype=uint8)


In [284]:
def get_shape(tensor):
    return tensor.shape[0], tensor.shape[1]

#max_height, max_width = merged_df['image_data'].apply(lambda x: get_shape(x),).max()
max_height_array, max_width_array = [], []
for i in merged_df['image_data']:
    newmax_height, newmax_width = get_shape(i)
    max_height_array.append(newmax_height)
    max_width_array.append(newmax_width)


print("Maximum height:", max(max_height_array))
print("Maximum width:", max(max_width_array))

Maximum height: 2828
Maximum width: 3408


In [285]:
# Assuming merged_df contains your DataFrame with image tensors

# Define the target height and width
target_height = 2828
target_width = 3408

# Define a function to pad images
def pad_image(image_tensor):
    # Calculate the height and width difference
    pad_height = target_height - image_tensor.shape[0]
    pad_width = target_width - image_tensor.shape[1]

    # Pad the image tensor with zeros
    padded_image = tf.pad(image_tensor, paddings=[[0, pad_height], [0, pad_width]], mode='CONSTANT', constant_values=0)

    return padded_image

# Apply the pad_image function to all images in the DataFrame
merged_df['padded_image'] = merged_df['image_data'].apply(pad_image)

# Check the padded images
print(merged_df['padded_image'])

0      ((tf.Tensor(33, shape=(), dtype=uint8), tf.Ten...
1      ((tf.Tensor(2, shape=(), dtype=uint8), tf.Tens...
2      ((tf.Tensor(33, shape=(), dtype=uint8), tf.Ten...
3      ((tf.Tensor(22, shape=(), dtype=uint8), tf.Ten...
4      ((tf.Tensor(102, shape=(), dtype=uint8), tf.Te...
                             ...                        
174    ((tf.Tensor(37, shape=(), dtype=uint8), tf.Ten...
175    ((tf.Tensor(21, shape=(), dtype=uint8), tf.Ten...
176    ((tf.Tensor(13, shape=(), dtype=uint8), tf.Ten...
177    ((tf.Tensor(11, shape=(), dtype=uint8), tf.Ten...
178    ((tf.Tensor(29, shape=(), dtype=uint8), tf.Ten...
Name: padded_image, Length: 179, dtype: object


In [297]:
# Splitting the DataFrame into features (X) and labels (y)
X = np.stack(merged_df['padded_image'])
y = merged_df.drop(['filename', 'image_data','padded_image'], axis=1)

# One-hot encode the labels
y = pd.get_dummies(y, dummy_na=True)

# Splitting the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = np.reshape(X_train, (*X_train.shape, 1))
X_val = np.reshape(X_val, (*X_val.shape, 1))
print(X,y)

[[[33 32 32 ...  0  0  0]
  [32 31 31 ...  0  0  0]
  [31 30 31 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[ 2  2  2 ...  0  0  0]
  [ 2  2  2 ...  0  0  0]
  [ 2  2  2 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[33 29 27 ...  0  0  0]
  [32 28 26 ...  0  0  0]
  [32 28 26 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 ...

 [[13 14 15 ...  0  0  0]
  [16 11 14 ...  0  0  0]
  [15  8 11 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[11 12 13 ...  0  0  0]
  [13 12 11 ...  0  0  0]
  [19 17 15 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]

 [[29 55 31 ...  0  0  0]
  [66 18 23 ...  0  0  0]
  [57 68 36 ...  0  0  0]
  ...
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]
  [ 0  0  0 ...  0  0  0]]]      No Fi

# Need to Specifiy the channel size. 

In [298]:
# Define the CNN architecture
model = Sequential([
    Conv2D(64, (3, 3), activation='relu', input_shape=X_train.shape[1:]),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dropout(0.2),
    Dense(512, activation='relu'),
    Dense(3, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))

# Unspecified Data Resizing Attemps


In [ ]:
# Define a function to resize images
def resize_image(image_tensor, target_size=(256, 256)):
    resized_image = tf.image.resize(image_tensor, target_size)
    return resized_image.numpy()  # Convert back to NumPy array

# Resize all images and stack them into a NumPy array
resized_images = merged_df['image_data'].apply(lambda x: resize_image(x))
X = np.stack(resized_images.values)

ValueError: 'images' must have either 3 or 4 dimensions.

In [ ]:
# Assuming merge_df contains your merged DataFrame with image data and classification labels
# Convert image_data from strings to numpy arrays
#merged_df['image_data'] = merged_df['image_data'].apply(lambda x: np.array(eval(x)))

dat_F_X = merged_df['image_data'].values

image_lengths = [len(image_data) for image_data in merged_df['image_data'].values]
print(image_lengths)

[2320, 2320, 2320, 2320, 2022, 2320, 2021, 2048, 2320, 2320, 2320, 2010, 2320, 2048, 2048, 2320, 2320, 2320, 2016, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2021, 2320, 2048, 2320, 2320, 2320, 2320, 2320, 2320, 2021, 2320, 2021, 1671, 2320, 2320, 2320, 2320, 2320, 2320, 2022, 2320, 2320, 2022, 2016, 1741, 2014, 2800, 2320, 2320, 2320, 2048, 2021, 2021, 2828, 2022, 1826, 2022, 2320, 2828, 2320, 2320, 2320, 2320, 2320, 2048, 2320, 2320, 2548, 2320, 2320, 2800, 2320, 2016, 2320, 2021, 2320, 2022, 2022, 2320, 2021, 2320, 2320, 2320, 2320, 2320, 2320, 2800, 2011, 1751, 2021, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2800, 2800, 1910, 2048, 2320, 2320, 2320, 1751, 2320, 1751, 2021, 2320, 2800, 2828, 2828, 2048, 2022, 2548, 2800, 1751, 2320, 2048, 2320, 2021, 2320, 2021, 2320, 2320, 2320, 1964, 2320, 2022, 1751, 2320, 1830, 1741, 1601, 2320, 2320, 2800, 2320, 2320, 2022, 2320, 2828, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2320, 2021, 2320, 1751, 2800, 2022, 2320, 2800, 232

In [ ]:
from PIL import Image

# Assuming merged_df contains your DataFrame with image data
# Convert image_data from string to numpy array
merged_df['image_data'] = merged_df['image_data'].apply(lambda x: np.array(x))

# Find the maximum width and height among all images
max_width = max(img.shape[1] for img in merged_df['image_data'])
max_height = max(img.shape[0] for img in merged_df['image_data'])

# Define a function to resize images while maintaining aspect ratio
def resize_with_aspect_ratio(img, target_width, target_height):
    # Calculate the scaling factor for width and height
    width_ratio = target_width / img.shape[1]
    height_ratio = target_height / img.shape[0]
    # Choose the minimum scaling factor to maintain aspect ratio
    min_ratio = min(width_ratio, height_ratio)
    # Resize the image with the minimum scaling factor
    resized_img = Image.fromarray(img).resize((int(img.shape[1] * min_ratio), int(img.shape[0] * min_ratio)))
    return np.array(resized_img)

# Apply resizing to all images in the DataFrame
merged_df['resized_image_data'] = merged_df['image_data'].apply(lambda img: resize_with_aspect_ratio(img, max_width, max_height))
merged_df.head()
# Now, merged_df['resized_image_data'] contains resized images with maintained aspect ratio
# You can convert these resized images back to a string representation if needed
# merged_df['resized_image_data'] = merged_df['resized_image_data'].apply(lambda img: img.tolist())

# Optionally, save the DataFrame to a new CSV file
#merged_df.to_csv('resized_images.csv', index=False)


filename                                         image_data AP/PA  \
0  image_178.jpg  [[33, 32, 32, 30, 31, 31, 29, 32, 32, 29, 32, ...    AP   
1  image_150.jpg  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...     0   
2  image_144.jpg  [[33, 29, 27, 27, 26, 24, 21, 18, 15, 4, 1, 0,...    PA   
3   image_15.jpg  [[22, 19, 17, 17, 17, 18, 17, 17, 17, 20, 19, ...    AP   
4   image_29.jpg  [[102, 106, 115, 96, 99, 119, 93, 102, 123, 10...    AP   

   No Finding  Enlarged Cardiomediastinum  Cardiomegaly  Lung Opacity  \
0         1.0                         0.0           0.0           0.0   
1         1.0                         0.0           0.0           0.0   
2         1.0                         0.0           0.0           0.0   
3         1.0                        -1.0           0.0          -1.0   
4         0.0                         0.0           0.0           0.0   

   Pneumonia  Pleural Effusion  Pleural Other  Fracture  Support Devices  \
0        0.0               0.0            0.0       0.0              1.0   
1        0.0               0.0            0.0       0.0              1.0   
2        0.0              -1.0            0.0       0.0              0.0   
3        0.0              -1.0            0.0       0.0              0.0   
4        0.0               0.0            0.0       0.0              0.0   

                                  resized_image_data  
0  [[33, 32, 32, 31, 30, 31, 31, 29, 31, 32, 31, ...  
1  [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...  
2  [[33, 30, 28, 27, 27, 26, 24, 22, 19, 17, 13, ...  
3  [[22, 20, 18, 17, 17, 17, 18, 17, 17, 17, 18, ...  
4  [[101, 103, 109, 115, 101, 95, 101, 119, 104, ...

In [ ]:
merged_df['image_data'].values.shape

(179,)

In [ ]:
tf.reshape?

Signature: tf.reshape(tensor, shape, name=None)
Docstring:
Reshapes a tensor.

Given `tensor`, this operation returns a new `tf.Tensor` that has the same
values as `tensor` in the same order, except with a new shape given by
`shape`.

>>> t1 = [[1, 2, 3],
...       [4, 5, 6]]
>>> print(tf.shape(t1).numpy())
[2 3]
>>> t2 = tf.reshape(t1, [6])
>>> t2
<tf.Tensor: shape=(6,), dtype=int32,
  numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
>>> tf.reshape(t2, [3, 2])
<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
  array([[1, 2],
         [3, 4],
         [5, 6]], dtype=int32)>

The `tf.reshape` does not change the order of or the total number of elements
in the tensor, and so it can reuse the underlying data buffer. This makes it
a fast operation independent of how big of a tensor it is operating on.

>>> tf.reshape([1, 2, 3], [2, 2])
Traceback (most recent call last):
...
InvalidArgumentError: Input to reshape is a tensor with 3 values, but the
requested shape has 4

To instead reorder the dat

In [ ]:
reshaped_images = tf.reshape(image_tensors, [256, 256])

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type tensorflow.python.framework.ops.EagerTensor).

In [ ]:
resized_image_lengths = [len(image_data) for image_data in merged_df['resized_image_data'].values]
print(resized_image_lengths)

[2795, 2795, 2795, 2795, 2828, 2795, 2828, 2798, 2795, 2795, 2795, 2828, 2795, 2798, 2798, 2795, 2795, 2795, 2828, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2828, 2795, 2798, 2795, 2795, 2795, 2795, 2795, 2795, 2828, 2795, 2828, 2828, 2795, 2795, 2795, 2795, 2795, 2795, 2828, 2795, 2795, 2828, 2828, 2828, 2828, 2828, 2795, 2795, 2795, 2798, 2828, 2828, 2828, 2828, 2828, 2828, 2795, 2828, 2795, 2795, 2795, 2795, 2795, 2798, 2795, 2795, 2828, 2795, 2795, 2800, 2795, 2828, 2795, 2828, 2795, 2828, 2828, 2795, 2828, 2795, 2795, 2795, 2795, 2795, 2795, 2800, 2828, 2828, 2828, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2800, 2800, 2828, 2798, 2795, 2795, 2795, 2828, 2795, 2828, 2828, 2795, 2828, 2828, 2828, 2798, 2828, 2828, 2800, 2828, 2795, 2798, 2795, 2828, 2795, 2828, 2795, 2795, 2795, 2828, 2795, 2828, 2828, 2795, 2828, 2828, 2828, 2795, 2795, 2828, 2795, 2795, 2828, 2795, 2828, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2795, 2828, 2795, 2828, 2828, 2828, 2795, 2800, 279

In [ ]:
# Splitting the DataFrame into features (X) and labels (y)
X = np.stack(X_bar)
y = merged_df.drop(['filename', 'image_data','padded_image_data'], axis=1)
print(X, y)

# One-hot encode the labels
y = pd.get_dummies(y, dummy_na=True)

# Splitting the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Define the CNN architecture
model = Sequential([
    Conv2D(64, (3, 3), activation='relu', input_shape=X_train.shape[1:]),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dropout(0.2),
    Dense(512, activation='relu'),
    Dense(3, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))